---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: conforma-controller
        control-plane: controller-manager
    spec:
      serviceAccountName: manager
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: controller
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          args:
            - --metrics-bind-address=:8443
            - --metrics-secure=true
            - --health-probe-bind-address=:8081
            - --leader-elect=false
          env:
            - name: VALIDATOR_IMAGE
              value: quay.io/conforma/cli:snapshot
            - name: VALIDATOR_SA
              value: default
          ports:
            - name: https-metrics
              containerPort: 8443
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
            initialDelaySeconds: 5
            timeoutSeconds: 5
